# Generated by Django 5.2.4 on 2025-08-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_remove_route_route_id_remove_stop_stop_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestop',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='routestop',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
