# Generated by Django 5.2.4 on 2025-07-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_alter_bus_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_id',
        ),
        migrations.AlterField(
            model_name='bus',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
