# Generated by Django 5.2.4 on 2025-07-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoprequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoprequest',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
