# Generated by Django 5.2.4 on 2025-08-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoprequests', '0002_alter_stoprequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoprequest',
            name='id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
